-- MySQL Script generated by MySQL Workbench
-- Tue Apr 28 09:31:14 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mustruobd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mustruobd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mustruobd` DEFAULT CHARACTER SET utf8 ;
USE `mustruobd` ;

-- -----------------------------------------------------
-- Table `mustruobd`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mustruobd`.`rol` (
  `id` INT NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mustruobd`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mustruobd`.`usuario` (
  `login` VARCHAR(20) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `imagen` VARCHAR(45) NULL,
  `contrasenna` VARCHAR(100) NOT NULL,
  `rol_id` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`login`),
  INDEX `fk_usuario_rol_idx` (`rol_id` ASC) ,
  CONSTRAINT `fk_usuario_rol`
    FOREIGN KEY (`rol_id`)
    REFERENCES `mustruobd`.`rol` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mustruobd`.`privacidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mustruobd`.`privacidad` (
  `id` INT NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mustruobd`.`estado_mesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mustruobd`.`estado_mesa` (
  `id` INT NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mustruobd`.`mesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mustruobd`.`mesa` (
  `id_mesa` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NOT NULL,
  `contrasenna` VARCHAR(45) NULL,
  `privacidad_id` INT NOT NULL,
  `vacas` INT NOT NULL DEFAULT 2,
  `juegos` INT NOT NULL DEFAULT 3,
  `puntos` INT NOT NULL DEFAULT 30,
  `login` VARCHAR(20) NOT NULL,
  `estado` INT NOT NULL,  
  PRIMARY KEY (`id_mesa`),
  INDEX `fk_mesa_privacidad1_idx` (`privacidad_id` ASC) ,
  INDEX `fk_mesa_usuario1_idx` (`login` ASC) ,
  INDEX `fk_mesa_estado_mesa1_idx` (`estado` ASC) ,
  CONSTRAINT `fk_mesa_privacidad1`
    FOREIGN KEY (`privacidad_id`)
    REFERENCES `mustruobd`.`privacidad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mesa_usuario1`
    FOREIGN KEY (`login`)
    REFERENCES `mustruobd`.`usuario` (`login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mesa_estado_mesa1`
    FOREIGN KEY (`estado`)
    REFERENCES `mustruobd`.`estado_mesa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mustruobd`.`pareja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mustruobd`.`pareja` (
  `id` INT NOT NULL,
  `descripcion` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mustruobd`.`usuarios_por_mesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mustruobd`.`usuarios_por_mesa` (
  `login` VARCHAR(20) NOT NULL,
  `mesa_id` INT NOT NULL,
  `pareja_id` INT NOT NULL,
  `posicion` INT NOT NULL,
  PRIMARY KEY (`login`),
  INDEX `fk_usuario_has_mesa_mesa1_idx` (`mesa_id` ASC) ,
  INDEX `fk_usuario_has_mesa_usuario1_idx` (`login` ASC),
  INDEX `fk_usuarios_por_mesa_pareja1_idx` (`pareja_id` ASC),
  CONSTRAINT `fk_usuario_has_mesa_usuario1`
    FOREIGN KEY (`login`)
    REFERENCES `mustruobd`.`usuario` (`login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_mesa_mesa1`
    FOREIGN KEY (`mesa_id`)
    REFERENCES `mustruobd`.`mesa` (`id_mesa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_por_mesa_pareja1`
    FOREIGN KEY (`pareja_id`)
    REFERENCES `mustruobd`.`pareja` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mustruobd`.`marcador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mustruobd`.`marcador` (
  `mesa_id` INT NOT NULL,
  `pareja_id` INT NOT NULL,
  `puntos` INT NOT NULL DEFAULT 0,
  `juegos` INT NOT NULL DEFAULT 0,
  `vacas` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`mesa_id`, `pareja_id`),
  INDEX `fk_mesa_has_pareja_pareja1_idx` (`pareja_id` ASC),
  INDEX `fk_mesa_has_pareja_mesa1_idx` (`mesa_id` ASC),
  CONSTRAINT `fk_mesa_has_pareja_mesa1`
    FOREIGN KEY (`mesa_id`)
    REFERENCES `mustruobd`.`mesa` (`id_mesa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mesa_has_pareja_pareja1`
    FOREIGN KEY (`pareja_id`)
    REFERENCES `mustruobd`.`pareja` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mustruobd`.`jugadas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mustruobd`.`jugadas` (
  `mesa_id` INT NOT NULL,
  `mano` INT NOT NULL,
  `estado` VARCHAR(45) NOT NULL DEFAULT 'repartir',
  `turno` INT NOT NULL,
  `jugada` VARCHAR(45) NOT NULL DEFAULT 'mus',
  `grande` VARCHAR(45) NOT NULL DEFAULT '-',
  `chica` VARCHAR(45) NOT NULL DEFAULT '-',
  `pares` VARCHAR(45) NOT NULL DEFAULT '-',
  `juego` VARCHAR(45) NOT NULL DEFAULT '-',
  `punto` VARCHAR(45) NOT NULL DEFAULT '-',
  `acumulado` INT NOT NULL DEFAULT 0,
  `rechazo` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`mesa_id`),
  INDEX `fk_mesa_has_pareja_mesa2_idx` (`mesa_id` ASC),
  CONSTRAINT `fk_mesa_has_pareja_mesa2`
    FOREIGN KEY (`mesa_id`)
    REFERENCES `mustruobd`.`mesa` (`id_mesa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mustruobd`.`estadisticas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mustruobd`.`estadisticas` (
  `juegos_jugados` INT NOT NULL DEFAULT 0,
  `juegos_ganados` INT NOT NULL DEFAULT 0,
  `vacas_jugadas` INT NOT NULL DEFAULT 0,
  `vacas_ganadas` INT NOT NULL DEFAULT 0,
  `abandonos` INT NOT NULL DEFAULT 0,
  `login` VARCHAR(20) NOT NULL,
  `mustruo_semana` INT NOT NULL DEFAULT 0,
  `mustruo_mes` INT NOT NULL DEFAULT 0,
  `mustruo_anno` INT NULL DEFAULT 0,
  INDEX `fk_estadisticas_usuario1_idx` (`login` ASC),
  PRIMARY KEY (`login`),
  CONSTRAINT `fk_estadisticas_usuario1`
    FOREIGN KEY (`login`)
    REFERENCES `mustruobd`.`usuario` (`login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mustruobd`.`tipo_mustruo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mustruobd`.`tipo_mustruo` (
  `id` INT NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mustruobd`.`mustruo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mustruobd`.`mustruo` (
  `fecha` VARCHAR(45) NOT NULL,
  `login` VARCHAR(20) NOT NULL,
  `tipo` INT NOT NULL,
  PRIMARY KEY (`fecha`, `login`),
  INDEX `fk_mustruo_usuario1_idx` (`login` ASC),
  INDEX `fk_mustruo_tipo_mustruo1_idx` (`tipo` ASC),
  CONSTRAINT `fk_mustruo_usuario1`
    FOREIGN KEY (`login`)
    REFERENCES `mustruobd`.`usuario` (`login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mustruo_tipo_mustruo1`
    FOREIGN KEY (`tipo`)
    REFERENCES `mustruobd`.`tipo_mustruo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mustruobd`.`estado_cartas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mustruobd`.`estado_cartas` (
  `id` INT NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mustruobd`.`cartas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mustruobd`.`cartas` (
  `mesa_id` INT NOT NULL,
  `numero` INT NOT NULL,
  `palo` VARCHAR(10) NOT NULL,
  `imagen` VARCHAR(45) NOT NULL,
  `valor` INT NOT NULL,
  `estado` INT NOT NULL,
  PRIMARY KEY (`mesa_id`, `numero`, `palo`),
  INDEX `fk_cartas_estado_cartas1_idx` (`estado` ASC),
  CONSTRAINT `fk_cartas_mesa1`
    FOREIGN KEY (`mesa_id`)
    REFERENCES `mustruobd`.`mesa` (`id_mesa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cartas_estado_cartas1`
    FOREIGN KEY (`estado`)
    REFERENCES `mustruobd`.`estado_cartas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mustruobd`.`mustruo_temporal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mustruobd`.`mustruo_temporal` (
  `login` VARCHAR(20) NOT NULL,
  `tipo_mustruo` INT NOT NULL,
  `juegos_jugados` INT NULL DEFAULT 0,
  `juegos_ganados` INT NULL DEFAULT 0,
  `vacas_jugadas` INT NULL DEFAULT 0,
  `vacas_ganadas` INT NULL DEFAULT 0,
  `puntos` INT NULL DEFAULT 0,
  PRIMARY KEY (`login`, `tipo_mustruo`),
  INDEX `fk_mustruo_temporal_tipo_mustruo1_idx` (`tipo_mustruo` ASC),
  CONSTRAINT `fk_mustruo_temporal_usuario1`
    FOREIGN KEY (`login`)
    REFERENCES `mustruobd`.`usuario` (`login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mustruo_temporal_tipo_mustruo1`
    FOREIGN KEY (`tipo_mustruo`)
    REFERENCES `mustruobd`.`tipo_mustruo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- -----------------------------------------------------
-- Insercion roles
-- -----------------------------------------------------
INSERT INTO `rol` (`id`, `descripcion`) VALUES ('0', 'admin'), ('1', 'normal');

-- -----------------------------------------------------
-- Insercion parejas
-- -----------------------------------------------------
INSERT INTO `pareja` (`id`, `descripcion`) VALUES ('0', 'A'), ('1', 'B');

-- -----------------------------------------------------
-- Insercion privacidad
-- -----------------------------------------------------
INSERT INTO `privacidad` (`id`, `descripcion`) VALUES ('0', 'privada'), ('1', 'publica');

-- -----------------------------------------------------
-- Insercion tipo_mustruo
-- -----------------------------------------------------
INSERT INTO `tipo_mustruo` (`id`, `descripcion`) VALUES ('0', 'semanal'), ('1', 'mensual'), ('2', 'anual');

-- -----------------------------------------------------
-- Insercion administrador (admin, administrador)
-- -----------------------------------------------------
INSERT INTO `usuario` (`login`, `email`, `imagen`, `contrasenna`, `rol_id`) VALUES ('admin', 'admin_mustruo@gmail.com', 'anonimus.jpg', '$2y$10$vNaSRMtKhqqJ.Qbg1T0.se8L00GtrffdbuQBnVrJMDtlYbMcsXUfC', '0');
INSERT INTO `estadisticas` (`login`) VALUES ('admin');
INSERT INTO `mustruo_temporal` (`login`, `tipo_mustruo`) VALUES ('admin', '0'), ('admin', '1'), ('admin', '2');

-- -----------------------------------------------------
-- Insercion estado_cartas
-- -----------------------------------------------------
INSERT INTO `estado_cartas` (`id`, `descripcion`) VALUES ('0', 'jugador 0'), ('1', 'jugador 1'), ('2', 'jugador 2'), ('3', 'jugador 3'), ('4', 'baraja'), ('5', 'descarte');

-- -----------------------------------------------------
-- Insercion estado_mesa
-- -----------------------------------------------------
INSERT INTO `estado_mesa` (`id`, `descripcion`) VALUES ('0', 'En espera'), ('1', 'Jugando');