<?php global $URL_PATH;?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- Propia hoja de estilos -->
    <link rel="stylesheet" href="<?= $URL_PATH ?>/css/main.css">
    <link href="https://fonts.googleapis.com/css2?family=Special+Elite&display=swap" rel="stylesheet">
    <?php \dawfony\Ti::startBlock("extrahead"); ?>
    <?php \dawfony\Ti::endBlock() ?>
    <title>
        <?php \dawfony\Ti::startBlock("title"); ?>
        <?=$data["title"]?> - Mustruo
        <?php \dawfony\Ti::endBlock() ?>
    </title>
</head>
<body>
    <nav class="barraPrincipal">
        <div class="barraTitulo centrarTexto">
            <span><?=$data["title"]?></span>
        </div>
        <!--LOGO-->
        <div class="barraLogo">   
            <img src="<?= $URL_PATH ?>/media/logo.png">
        </div>
        <div class="barraLogin">
            <?php if (isset($enLobby)) : ?>
                <a class="boton-marron volverLobby centrarTexto" href="<?= $URL_PATH ?>/"><span>Volver a Lobby</span></a>
            <?php elseif (isset($_SESSION["login"])) : ?>
                <a class="irAPerfil centrarTexto" href="<?= $URL_PATH ?>/perfil/<?= $_SESSION["login"] ?>"><span>Ir a perfil</span></a>
                <a class="boton-marron cerrarSesion centrarTexto" href="<?= $URL_PATH ?>/cerrarSesion"><span>Cerrar Sesión</span></a>             
            <?php else : ?>
                <input type="text" class="inicioLogin" id="login" name="login" placeholder="usuario">
                <input type="password" class="inicioContrasenna" id="contrasenna" name="contrasenna" placeholder="************">
                <div class="inicioBotones">
                    <a href="javascript:void(0)" class="boton-marron iniciarSesion centrarTexto" id="comprobarSesion"><span>Iniciar Sesión</span></a>
                    <a class="registrate centrarTexto" href="<?= $URL_PATH ?>/registrate">Regístrate</a>
                </div>
                <script>
                    var URL_PATH = '<?= $URL_PATH ?>';
                </script>
            <?php endif; ?> 
        </div>
    </nav>
    <div class="contenedor">
    <?php \dawfony\Ti::startBlock("content"); ?>
    <?php \dawfony\Ti::endBlock() ?>
    </div>
</body>
</html>